# Generated by Django 5.2.14 on 2026-06-01 00:00

import hashlib
from django.db import migrations, models


def _compute_hash_for_page(page):
    if not page.image:
        return ''

    hasher = hashlib.sha256()
    page.image.open('rb')
    try:
        for chunk in page.image.chunks():
            hasher.update(chunk)
    finally:
        page.image.close()

    return hasher.hexdigest()


def populate_existing_image_hashes(apps, schema_editor):
    PageImage = apps.get_model('extractor', 'PageImage')
    pages = PageImage.objects.filter(image_hash='')

    for page in pages.iterator():
        try:
            page.image_hash = _compute_hash_for_page(page)
            page.save(update_fields=['image_hash'])
        except Exception:
            # Keep migration resilient even if a file is missing on disk.
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageimage',
            name='image_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.RunPython(populate_existing_image_hashes, migrations.RunPython.noop),
    ]
