# Generated by Django 5.2.14 on 2026-06-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractor", "0003_titlelookuptask"),
    ]

    operations = [
        migrations.AddField(
            model_name="titlelookuptask",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="titlelookuptask",
            name="current_title_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="titlelookuptask",
            name="total_titles",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="titlelookuptask",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("ERROR", "Error"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
