# Generated by Django 5.2.14 on 2026-06-09 21:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extractor", "0004_titlelookuptask_cancelled_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LookupTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("extract_fields", models.JSONField(default=list)),
                (
                    "search_query_template",
                    models.TextField(default='"{title}" "{isbn}" publication year'),
                ),
                (
                    "prompt_template",
                    models.TextField(
                        default="You are given a book title and ISBN plus search result snippets. Extract the following fields for this specific ISBN edition:\n{fields}\n\nAlways output valid JSON in this exact format:\n{schema}\n\nTitle: {title}\nISBN: {isbn}\n\nSearch snippets:\n{snippets}\n\nIf you cannot determine a field, return null for it. Be concise and honest about your confidence."
                    ),
                ),
                ("output_schema", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["is_system", "name"],
            },
        ),
        migrations.AddField(
            model_name="titlelookuptask",
            name="template_config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
